### ISSUE TITLE
rabbitmq HA solution

### ISSUE THREAD

**Issue by gauravyadav01** [sensu/sensu-puppet#541] opened 2016-08-22 14:03 UTC
Hi , 

It would be great if you add rabbitmq HA config to this module. 

such as 

{
  "rabbitmq": [
    {
      "host": "10.0.0.6",
      "port": 5671,
      "vhost": "/sensu",
      "user": "sensu",
      "password": "secret",
      "heartbeat": 30,
      "prefetch": 50,
      "ssl": {
        "cert_chain_file": "/etc/sensu/ssl/cert.pem",
        "private_key_file": "/etc/sensu/ssl/key.pem"
      }
    },
    {
      "host": "10.0.0.7",
      "port": 5671,
      "vhost": "/sensu",
      "user": "sensu",
      "password": "secret",
      "heartbeat": 30,
      "prefetch": 50,
      "ssl": {
        "cert_chain_file": "/etc/sensu/ssl/cert.pem",
        "private_key_file": "/etc/sensu/ssl/key.pem"
      }
    }
 ]
}

**Comment by jaxxstorm** [comment] 2016-08-22 14:21
This will be available when #518 is rebased and merged

**Comment by gauravyadav01** [comment] 2016-08-22 14:32
thanks...

**Comment by jaxxstorm** [comment] 2016-09-15 10:50
This is a duplicate of #269 so closing

**Closed by jaxxstorm** 2016-09-15 10:50 UTC
