### ISSUE TITLE
Error trying to apply a filter

### ISSUE THREAD

**Issue by zanloy** [sensu/sensu-puppet#375] opened 2015-06-23 17:13 UTC
I am trying to implement a filter and I keep getting an error trying to apply the catalog.

## Error message:
Error: /Stage[main]/Profiles::Sensu/Sensu::Handler[slack]/Sensu_handler[slack]/filters: change from  to maint_filter failed: undefined method `sort' for nil:NilClass

## Filter declaration:
```puppet
sensu::filter { 'maint_filter':
  attributes => { 'maint' => 'false' },
}
```

## Handler declaration:
```puppet
sensu::handler { 'slack':
  command => 'slack.rb',
  source  => 'puppet:///modules/profiles/sensu/handlers/slack.rb',
  config  => {
    'webhook_url' => '***FILTERED**',
    'channel'     => '#sensu',
  },
  mutator => 'maint_mode',
  filters => ['maint_filter'],
}
```

Any help would be greatly appreciated.

**Comment by rk295** [comment] 2015-06-23 17:15
Snap! Dupe of #374 I think :)

**Comment by zanloy** [comment] 2015-06-23 17:32
Oops. I did not see that issue already open.

**Closed** 2015-06-23 17:33 UTC
